### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by herpiko** [BlankOn/irgsh-web#13]
Then push it to hub.docker.com

**Comment by tuanpembual** [comment]
mari mencari pemilik akun blankon,
pak @herpiko coba japri pak dio

**Comment by herpiko** [comment]
# Langkah reka ulang

## Basis citra

Pull dari debian:stable-slim (jessie)

## Persiapan sistem 
```
$ apt-get update
$ apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils sudoers python python-pip python-dev python-debian dpkg-dev rabbitmq-server git-core nginx libpq-dev git vim
```

Tambah user `irgsh`, izinkan sudo, masuk sebagai user tersebut.

## Pasang pyenv / python 2.6.6

Pasang pakai `https://github.com/pyenv/pyenv-installer`

```
$ pyenv instal 2.6.6
$ pyenv shell 2.6.6
```

Selanjutnya di dalam `2.6.6`

## Kloning repositori
```
$ mkdir src
$ cd src
$ git clone git://github.com/BlankOn/python-irgsh.git
$ git clone git://github.com/BlankOn/irgsh-web.git
$ git clone git://github.com/BlankOn/irgsh-node.git
$ git clone git://github.com/BlankOn/irgsh-repo.git
$ cd irgsh-web
$ ln -s ../python-irgsh/irgsh
$ ln -s ../irgsh-node/irgsh_node
$ ln -s ../irgsh-repo/irgsh_repo
```
## Bangun

```
$ python bootstrap.py
```

### Workaround untuk pyparsing
```
$ pip uninstall pyparsing
$ rm -rf eggs/pyparsing*`
```

Sunting baris 59 dari  `/home/irgsh/.pyenv/versions/2.6.6/lib/python2.6/site-packages/packaging/requirements.py`

Dari `MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")` ke `MARKER_EXPR = originalTextFor(MARKER_EXPR)("marker")`.


Lalu `pip install pyparsing==1.5.7`, ulangi 2 kali

### Buildout 
```
./bin/buildout
```

### Pasang paket python pendukung lainnya
```
$ pip install -r requirements.txt
```

**Comment by showcheap** [comment]
Jika muncul masalah / galat seperti ini
```
root@adeb31b4354a:~/src/irgsh-web# pip install pyparsing==1.5.7
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting pyparsing==1.5.7
  Using cached pyparsing-1.5.7.zip
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.6.6/lib/python2.6/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/root/.pyenv/versions/2.6.6/lib/python2.6/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/root/.pyenv/versions/2.6.6/lib/python2.6/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/root/.pyenv/versions/2.6.6/lib/python2.6/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/root/.pyenv/versions/2.6.6/lib/python2.6/site-packages/packaging/requirements.py", line 9, in <module>
    from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
ImportError: No module named pyparsing
```
Bisa coba untuk downgrade setuptools
`pip install setuptools==19.2 `

**Comment by herpiko** [comment]
@showcheap berarti sudah berbeda lagi dengan setuptools yang dipakai di bootstrap / buildout?

**Comment by herpiko** [comment]
@showcheap coba ini pak,

```
$ rm -rf eggs/pyparsing*
$ pip uninstall pyparsing
$ pip install pyparsing
$ pip install pyparsing==1.5.7
```

**Comment by i5um41ru** [comment]
Mirip dengan irgsh-node ya prosedur reka ulangnya pak.

**Comment by herpiko** [comment]
Done by @showcheap https://github.com/showcheap/irgsh-web-docker

**Comment by herpiko** [comment]
Please move the dockerfile to this repo.
